In [ ]:
import tensorflow as tf
import numpy as np

def f(x):
  return tf.reduce_sum(tf.pow(tf.stack([x,x,x,x]), [1,2,3,4]))


print(f(0), f(1), f(2))

x = tf.Variable([-1], dtype=tf.float64)
with tf.GradientTape() as gt:
  y = f(x)
fprime = gt.gradient(y, x)
print(fprime)

x = tf.Variable(-1, dtype=tf.float64)
with tf.GradientTape() as gt:
  y = f(x)
fprime2 = tf.pow(gt.gradient(y, x), 2)
print(fprime2)

tf.Tensor(0, shape=(), dtype=int32) tf.Tensor(4, shape=(), dtype=int32) tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor([-2.], shape=(1,), dtype=float64)
tf.Tensor([64.], shape=(1,), dtype=float64)


In [ ]:
# vector - scalar

def f(x):
  return tf.reduce_sum(tf.pow(x, 3))


#a
x1 = tf.constant([1., 2., 3.], dtype=tf.float64)
x2 = tf.constant([2., 0., 2.], dtype=tf.float64)

print(f(x1), f(x2))

#b
x = tf.Variable(initial_value=[0, 0, 0], dtype=tf.float64)
x.assign(x1)
with tf.GradientTape() as gt:
  y = f(x)
gradf = gt.gradient(y, x)
print(gradf.numpy())

#c
x = tf.Variable(initial_value=[0,0,0], dtype=tf.float64)
x.assign(x2)
with tf.GradientTape() as gt:
  y = f(x)
fprime2 = gt.gradient(y, x)
print(fprime2.numpy()[0])

tf.Tensor(36.0, shape=(), dtype=float64) tf.Tensor(16.0, shape=(), dtype=float64)
[ 3. 12. 27.]
12.0


In [ ]:
#3 Vector-Vector chain rule in TF

#a
W = tf.constant([1, 2, -1, 1, 0, 1], dtype=tf.float64, shape=(3,2))

def f(x):
  return tf.matmul(W, x)

def g(x):
  return tf.reduce_sum(x)

x1 = tf.constant([1, 2], dtype=tf.float64, shape=(2,1))
x2 = tf.constant([2, 0], dtype=tf.float64, shape=(2,1))

h = g(f(x1))
h1 = g(f(x2))
print(h, h1)

#b
x = tf.Variable(initial_value=x1, dtype=tf.float64)
with tf.GradientTape() as gt:
  y = g(f(x))
frpime = gt.gradient(y, x)
print(frpime.numpy())

#c
with tf.GradientTape() as gt:
  gt.watch(W)
  y = g(f(x))
mat = gt.gradient(y, W)
print(mat.numpy())



tf.Tensor(8.0, shape=(), dtype=float64) tf.Tensor(0.0, shape=(), dtype=float64)
[[0.]
 [4.]]
[[1. 2.]
 [1. 2.]
 [1. 2.]]
